name: Test Documentation

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    # Skip docs if 'skip docs' is contained in latest commit message
    if: "!contains(github.event.head_commit.message, 'skip docs')"

    steps:

    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[docs]"

    - name: Build documentation
      run: |
        cd docs
        make clean
        make html
